### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by easybest**

### CODE REVIEW

**Comment by kopax** [comment]
I have tried to pull this and build and I have this error : 

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of constructor in org.springframework.data.mybatis.repository.support.MybatisRepositoryFactoryBean required a bean of type 'java.lang.Class' that could not be found.


Action:

Consider defining a bean of type 'java.lang.Class' in your configuration.

```

Is there a way to test the `@OneToMany` annotation ?

**Comment by easybest** [comment]
you should use spring-data commons with version 1.13.0.RELEASE

**Comment by kopax** [comment]
Thanks, I though the _1.4.4.RELEASE_ was the release I wanted.

I have just updated from _1.4.4.RELEASE_ to _[1.5.1.RELEASE](http://search.maven.org/#artifactdetails%7Corg.springframework.boot%7Cspring-boot-gradle-plugin%7C1.5.1.RELEASE%7Cjar)_

I now have `org.springframework.data:spring-data-commons:1.13.0.RELEASE` in my dependencies.

I have this error 

    org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'java.lang.Class<org.springframework.data.repository.Repository<?, ?>>' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}


I am trying to trace the error, do you know it ?

**Comment by kopax** [comment]
I have now upgraded to spring-boot 1.5.1.RELEASE which include 1.13.0.RELEASE of spring-data-commons. Thanks

**Pull request merged**
