### PR TITLE
1.0.13.RELEASE

### PR DESCRIPTION
**Pull request by easybest**

### CODE REVIEW

**Comment by kopax** [comment]
> resolved a serious bug

Thanks, could I have some more details ? I don't see any changelog or upcoming features.
Will you take care of keeping the API the same ? Will you update the changelog ready ?

**Comment by easybest** [comment]
The API will keep the same.

**Comment by easybest** [comment]
hi @kopax , if you have time , welcome you to maintain this project and documentation together

**Comment by kopax** [comment]
Hi @hatunet, thanks for the trust. I am starting up my startup so if you wan't I can hire you and you come to work with me in Vietnam. :) But seriously (we are really looking for a spring developer), I miss time to work on spring right now, we are mainly focusing our effort in UX first (reactjs). 

I should start actively using my spring app (and this plugin) around the end of the year.

Meanwhile, I can try to group all the information I have and prepare a documentation update using the current documentation. We need to do some sort of cleaning first. We can append to the doc little by little part and only the valuable information (spring-data-mybatis specific).

What do you think ?

**Pull request merged**
